KERNEL_POLITICALINFORMATION_MODEL = 'shell.PoliticalInformation'
KERNEL_DEPARTMENT_MODEL = 'shell.Department'
KERNEL_CENTRE_MODEL = 'shell.Centre'
KERNEL_BRANCH_MODEL = 'shell.Branch'
KERNEL_STUDENT_MODEL = 'shell.Student'
KERNEL_FACULTYMEMBER_MODEL = 'shell.FacultyMember'
