# Generated by Django 2.1.3 on 2018-11-29 12:13

import django.db.models.deletion
import swapper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # These ensure that whatever shell (or shells) define the following models are migrated before this migration
        swapper.dependency('kernel', 'Person'),
        swapper.dependency('kernel', 'Branch'),
        swapper.dependency('kernel', 'Course'),
        swapper.dependency('kernel', 'Degree'),
        swapper.dependency('kernel', 'Department'),

        # Explicit dependency on kernel.0001_models to prevent two leaf nodes in the migration graph
        ('kernel', '0001_models'),
    ]

    operations = [
        # Institute
        migrations.AddField(
            model_name='branch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Department')),
        ),
        migrations.AddField(
            model_name='branch',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Degree')),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Department')),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to=swapper.get_model_name('kernel', 'Course')),
        ),

        # Roles
        migrations.AddField(
            model_name='facultymember',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Department')),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Branch')),
        ),
        migrations.AddField(
            model_name='student',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='maintainer',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person')),
        ),

        # Auth
        migrations.AddField(
            model_name='person',
            name='local_guardians',
            field=models.ManyToManyField(blank=True, related_name='wards', to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='person',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='person',
            name='spouses',
            field=models.ManyToManyField(blank=True, related_name='_person_spouses_+', to=swapper.get_model_name('kernel', 'Person')),
        ),

        # Personal information
        migrations.AddField(
            model_name='financialinformation',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='politicalinformation',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='biologicalinformation',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='residentialinformation',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='residentialinformation',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Residence')),
        ),
    ]
