# Generated by Django 2.0.4 on 2018-08-28 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import swapper


class Migration(migrations.Migration):

    dependencies = [
        swapper.dependency('kernel', 'Department'),
        ('kernel', '0003_maintainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('credits', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
            ],
            options={
                'swappable': swapper.swappable_setting('kernel', 'Course'),
            },
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='centre',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolment_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Department')),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to=swapper.get_model_name('kernel', 'Course')),
        ),
    ]
