# Generated by Django 2.0.4 on 2018-09-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kernel', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('entity_object_id', models.PositiveIntegerField()),
                ('entity_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'social information',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('site', models.CharField(choices=[('beh', 'Behance'), ('blo', 'Blogger'), ('dri', 'Dribble'), ('fac', 'Facebook'), ('fli', 'Flickr'), ('git', 'Github'), ('goo', 'Google'), ('lin', 'LinkedIn'), ('med', 'Medium'), ('pin', 'Pinterest'), ('red', 'Reddit'), ('sky', 'Skype'), ('sna', 'Snapchat'), ('tum', 'Tumblr'), ('twi', 'Twitter'), ('you', 'YouTube'), ('oth', 'Other website')], max_length=7)),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='socialinformation',
            name='links',
            field=models.ManyToManyField(blank=True, to='kernel.SocialLink'),
        ),
    ]
