# Generated by Django 2.0.4 on 2018-09-01 22:08

from django.db import migrations, models
import kernel.utils.upload_to


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0004_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=kernel.utils.upload_to.UploadTo('kernel', 'display_pictures')),
        ),
    ]
