# Generated by Django 2.2.6 on 2020-01-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0004_auto_20200110_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
