# Generated by Django 2.2.6 on 2020-01-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0004_guest'),
        ('kernel', '0005_auto_20200110_2246'),
    ]

    operations = [
    ]
