# Generated by Django 3.2.8 on 2022-02-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kernel', '0006_merge_20200111_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'swappable': 'KERNEL_JOINTFACULTY_MODEL',
            },
        ),
        migrations.CreateModel(
            name='JointFacultyMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('entity_object_id', models.BigIntegerField()),
                ('designation', models.CharField(max_length=63)),
                ('entity_content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'shell'), ('model', 'department')), models.Q(('app_label', 'shell'), ('model', 'centre')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'swappable': 'KERNEL_JOINTFACULTYMEMBERSHIP_MODEL',
            },
        ),
    ]
