# Generated by Django 3.2.8 on 2022-02-06 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_JOINTFACULTYMEMBERSHIP_MODEL),
        ('kernel', '0007_jointfaculty_jointfacultymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointfaculty',
            name='memberships',
            field=models.ManyToManyField(related_name='joint_faculty_members', to=settings.KERNEL_JOINTFACULTYMEMBERSHIP_MODEL),
        ),
        migrations.AddField(
            model_name='jointfaculty',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_PERSON_MODEL),
        ),
    ]
