# Generated by Django 4.1.5 on 2023-09-27 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0008_auto_20220206_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='year_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='spouses',
            field=models.ManyToManyField(blank=True, to=settings.KERNEL_PERSON_MODEL),
        ),
    ]
