# Generated by Django 2.1.4 on 2018-12-15 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(max_length=63, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(max_length=255)),
                ('user_agent', models.CharField(max_length=255)),
                ('browser_family', models.CharField(max_length=31)),
                ('browser_version', models.CharField(max_length=31)),
                ('operating_system_family', models.CharField(max_length=31)),
                ('operating_system_version', models.CharField(max_length=31)),
                ('device_type', models.CharField(choices=[('com', 'Computer'), ('mob', 'Mobile'), ('tab', 'Tablet'), ('unk', 'Unknown device')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
