# Generated by Django 3.2 on 2022-04-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmap',
            name='user_agent',
            field=models.CharField(max_length=511),
        ),
    ]
