# Generated by Django 3.2 on 2022-06-22 19:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_auth', '0002_auto_20211016_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='data_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('person.short_name', 'Short name'), ('person.full_name', 'Full name'), ('person.display_picture', 'Display picture'), ('person.roles', 'Roles'), ('person.custom_roles', 'Custom Roles'), ('student.start_date', 'Joining date'), ('student.end_date', 'Graduation date'), ('student.enrolment_number', 'Enrolment number'), ('student.branch.name', 'Branch'), ('student.branch.degree.name', 'Degree'), ('student.current_year', 'Current year'), ('student.current_semester', 'Current semester'), ('student.branch.department.name', 'Department'), ('faculty_member.start_date', 'Joining date'), ('faculty_member.end_date', 'Leaving date'), ('faculty_member.designation', 'Designation'), ('faculty_member.department.name', 'Department'), ('biological_information.date_of_birth', 'Date of birth'), ('biological_information.blood_group', 'Blood group'), ('contact_information.email_address', 'Email address'), ('contact_information.email_address_verified', 'Email address verified'), ('contact_information.institute_webmail_address', 'Institute webmail address'), ('contact_information.primary_phone_number', 'Primary phone number'), ('contact_information.secondary_phone_number', 'Secondary phone number'), ('residential_information.residence.name', 'Residence'), ('residential_information.room_number', 'Room Number'), ('social_information.links', 'Links')], max_length=127), size=None),
        ),
    ]
