# Generated by Django 2.0.4 on 2018-04-28 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_PERSON_MODEL),
        ('shell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('post', models.CharField(blank=True, max_length=127)),
                ('role', models.CharField(choices=[('dev', 'Developer'), ('des', 'Designer'), ('duo', 'Dual role')], max_length=3)),
                ('designation', models.CharField(choices=[('web', 'Webmaster'), ('hub', 'Hub coordinator'), ('pro', 'Project leader'), ('coo', 'Coordinator'), ('adv', 'Technical adviser')], max_length=3)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_PERSON_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
