# Generated by Django 2.0.3 on 2018-04-03 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kernel.mixins.period_mixin


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_PERSON_MODEL),
        ('shell', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(choices=[('af', 'Adjunct faculty'), ('ap', 'Assistant professor'), ('apc', 'Assistant professor (contract)'), ('aws', 'Assistant workshop superintendent'), ('asp', 'Associate professor'), ('cp', 'Chair professor'), ('cso', 'Chief scientific officer'), ('dif', 'DST INSPIRE faculty'), ('emf', 'Emeritus fellow'), ('ep', 'Emeritus professor'), ('ef', 'Ex faculty'), ('gf', 'Guest faculty'), ('hoc', 'Head of centre'), ('hod', 'Head of department'), ('jp', 'Joint professor'), ('lec', 'Lecturer'), ('pro', 'Professor'), ('raf', 'Ramanujan fellow'), ('ref', 'Retired faculty'), ('so', 'Scientific officer'), ('sso', 'Senior scientific officer'), ('sp', 'System programmer'), ('vp', 'Visiting professor'), ('vs', 'Visiting scientist'), ('ws', 'Workshop superintendent')], max_length=3)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_DEPARTMENT_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_PERSON_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(kernel.mixins.period_mixin.PeriodMixin, models.Model),
        ),
    ]
