# Generated by Django 2.0.3 on 2018-03-29 10:52

import swapper

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiologicalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('gender', models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('n-bin', 'Non-binary/Other'), ('n-dis', 'Prefer not to disclose')], max_length=7)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('n-bin', 'Non-binary/Other'), ('n-dis', 'Prefer not to disclose')], max_length=7)),
                ('pronoun', models.CharField(choices=[('h', 'He/him/his'), ('s', 'She/her/her'), ('t', 'They/them/their')], max_length=1)),
                ('impairment', models.CharField(choices=[('o', 'Orthopaedically impaired'), ('v', 'Visually impaired'), ('h', 'Hearing impaired'), ('s', 'Speech impaired'), ('n', 'No impairment')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'biological information',
                'swappable': swapper.swappable_setting('kernel', 'BiologicalInformation'),
            },
        ),
        migrations.CreateModel(
            name='FinancialInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('local_bank', models.CharField(blank=True, max_length=63)),
                ('local_bank_account_number', models.CharField(blank=True, max_length=31)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=31, null=True)),
            ],
            options={
                'verbose_name_plural': 'financial information',
                'swappable':swapper.swappable_setting('kernel', 'FinancialInformation'),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('short_name', models.CharField(blank=True, max_length=63)),
                ('full_name', models.CharField(max_length=255)),
                ('local_guardians', models.ManyToManyField(blank=True, related_name='wards', to=settings.KERNEL_PERSON_MODEL)),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to=settings.KERNEL_PERSON_MODEL)),
                ('spouses', models.ManyToManyField(blank=True, related_name='_person_spouses_+', to=settings.KERNEL_PERSON_MODEL)),
            ],
            options={
                'swappable': swapper.swappable_setting('kernel', 'Person'),
            },
        ),
        migrations.CreateModel(
            name='PoliticalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('religion', models.CharField(blank=True, max_length=15)),
                ('passport_number', models.CharField(blank=True, max_length=15)),
                ('driving_license_number', models.CharField(blank=True, max_length=31)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person'))),
            ],
            options={
                'verbose_name_plural': 'political information',
                'swappable': swapper.swappable_setting('kernel', 'PoliticalInformation'),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, default=None, max_length=15, null=True, unique=True)),
                ('secret_question', models.CharField(blank=True, max_length=127)),
                ('secret_answer', models.CharField(blank=True, max_length=2047)),
                ('failed_reset_attempts', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person'))),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='financialinformation',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='biologicalinformation',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person')),
        ),
    ]
