# Generated by Django 2.0.3 on 2018-04-04 00:04

import swapper

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_DEPARTMENT_MODEL),
        migrations.swappable_dependency(settings.KERNEL_BRANCH_MODEL),
        ('kernel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Branch')),
        ),
        migrations.AddField(
            model_name='student',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='politicalinformation',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='person',
            name='local_guardians',
            field=models.ManyToManyField(blank=True, related_name='wards', to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='person',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='person',
            name='spouses',
            field=models.ManyToManyField(blank=True, related_name='_person_spouses_+', to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='financialinformation',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Department')),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person')),
        ),
        migrations.AddField(
            model_name='branch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Department')),
        ),
        migrations.AddField(
            model_name='biologicalinformation',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person')),
        ),
    ]
