# Generated by Django 2.0.3 on 2018-03-29 13:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kernel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('primary_phone_number', models.CharField(max_length=15, unique=True)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('email_address_verified', models.BooleanField(default=False)),
                ('institute_webmail_address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('entity_object_id', models.PositiveIntegerField()),
                ('entity_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'contact information',
            },
        ),
        migrations.CreateModel(
            name='LocationInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=127)),
                ('state', models.CharField(max_length=127)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postal_code', models.IntegerField(validators=[django.core.validators.RegexValidator('[0-9]{3,9}')])),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('entity_object_id', models.PositiveIntegerField()),
                ('entity_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'location information',
            },
        ),
    ]
