# Generated by Django 2.0.3 on 2018-04-01 20:04

import swapper

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_DEPARTMENT_MODEL),
        ('kernel', '0002_contactinformation_locationinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('degree', models.CharField(max_length=63)),
                ('graduation', models.CharField(max_length=63)),
                ('semester_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'swappable': swapper.swappable_setting('kernel', 'Branch'),
            },
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=127)),
            ],
            options={
                'swappable': swapper.swappable_setting('kernel', 'Centre'),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=127)),
            ],
            options={
                'swappable': swapper.swappable_setting('kernel', 'Department'),
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Department')),
        ),
    ]
