# Generated by Django 2.0.3 on 2018-04-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0003_branch_centre_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
    ]
