# Generated by Django 2.0.3 on 2018-04-03 08:50

import swapper

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import kernel.mixins.period_mixin


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_BRANCH_MODEL),
        ('kernel', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('enrolment_number', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('current_year', models.IntegerField()),
                ('current_semester', models.IntegerField()),
                ('current_cgpa', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Branch'))),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=swapper.get_model_name('kernel', 'Person'))),
            ],
            options={
                'swappable': swapper.swappable_setting('kernel', 'Student'),
            },
            bases=(kernel.mixins.period_mixin.PeriodMixin, models.Model),
        ),
    ]
