# Generated by Django 2.0.3 on 2018-04-03 18:33

from django.db import migrations, models
import kernel.models.auth


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0006_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=kernel.models.auth.upload_to),
        ),
    ]
