# Generated by Django 3.0.3 on 2021-10-06 14:52

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(blank=True, max_length=63, null=True)),
                ('description', models.TextField()),
                ('permission_keys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), size=None)),
                ('access_token', models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True, unique=True)),
                ('ip_address_regex', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
